@supabaseUrl = http://localhost:3000/api

//Login and save JWT token
# @name login
POST {{supabaseUrl}}/auth/login
Content-Type: application/json

{
  "email": "frederick.vdkerckhove@telenet.be",
  "password": "kinkhoorn"
}
###

//Admin can see all reservations
//User can only see their own reservations
GET {{supabaseUrl}}/afspraken
Authorization: Bearer {{login.response.body.jwt}}
Content-Type: application/json
###

//Admin can create a reservation
POST {{supabaseUrl}}/afspraken/new
Authorization: Bearer {{login.response.body.jwt}}
Content-Type: application/json

{
  "date": "2026-07-01",
  "time": "10:00"
}
###

POST {{supabaseUrl}}/afspraken/confirm
Authorization: Bearer {{login.response.body.jwt}}
Content-Type: application/json

{
  "id": "44"
}
###

POST {{supabaseUrl}}/afspraken/cancel
Authorization: Bearer {{login.response.body.jwt}}
Content-Type: application/json

{
  "id": "44"
}
###

POST {{supabaseUrl}}/afspraken/assign
Authorization: Bearer {{login.response.body.jwt}}
Content-Type: application/json

{
  "id": "44",
  "reserved_for": "2957ff51-613c-40f9-a4ae-c0e19f048f48"
}
###

POST {{supabaseUrl}}/afspraken/delete
Authorization: Bearer {{login.response.body.jwt}}
Content-Type: application/json

{
  "id": "44"
}
###


