# @supabaseUrl = http://localhost:3000/api
@supabaseUrl = https://psycholooglouise.be/api

//Login as admin
POST {{supabaseUrl}}/auth/login
Content-Type: application/json

{
  "email": "frederick.vdkerckhove@telenet.be",
  "password": "kinkhoorn"
}
###

//Login as test user, no admin, should fail
POST {{supabaseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@test.be",
  "password": "kinkhoorn"
}
###

//Login as not existing user
POST {{supabaseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user@telenet.be",
  "password": "password"
}
###

//Logout
POST {{supabaseUrl}}/auth/logout
###

//Register does not exist
POST {{supabaseUrl}}/auth/register
Content-Type: application/json

{
  "email": "user1@telenet.be",
  "password": "password"
}
###

