@supabaseUrl = http://localhost:3000/api

@jwtToken = "eyJhbGciOiJFUzI1NiIsImtpZCI6IjJhNjM1ODc3LTExNzAtNDRjYS1iMzVlLWFmNjUxZTU0YjlkYSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2VudnRkc3hqbHJqYnNlZm9tcnpsLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIyOTU3ZmY1MS02MTNjLTQwZjktYTRhZS1jMGUxOWYwNDhmNDgiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc5Njc0NTczLCJpYXQiOjE3Nzk2NzA5NzMsImVtYWlsIjoiZnJlZGVyaWNrLnZka2VyY2tob3ZlQHRlbGVuZXQuYmUiLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiZnJlZGVyaWNrLnZka2VyY2tob3ZlQHRlbGVuZXQuYmUiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiIyOTU3ZmY1MS02MTNjLTQwZjktYTRhZS1jMGUxOWYwNDhmNDgifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc3OTY3MDk3M31dLCJzZXNzaW9uX2lkIjoiZTkyMmI1MzYtYzFjNC00YjM4LWEzZmYtNzJlZGYzZmEyZTBlIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.2_4hX5qi8M_3UEHTpmQ958OWRWW-p6mbGMLvtAd6rFgFvPCQgTXAJNYo_9QKOjkU1J617v6o_GT-fJC-l-nkNg"
//Get all users (admin only)
GET {{supabaseUrl}}/clienten
Authorization: Bearer {{jwtToken}}
Content-Type: application/json
###