# @supabaseUrl = http://localhost:3000/api
@supabaseUrl = https://psycholooglouise.be/api

//Login and save JWT token
# @name login
POST {{supabaseUrl}}/auth/login
Content-Type: application/json

{
  "email": "frederick.vdkerckhove@telenet.be",
  "password": "kinkhoorn"
}
###

# @name loginTestUser
POST {{supabaseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@test.be",
  "password": "kinkhoorn"
}

###

//Get all users (admin only)
GET {{supabaseUrl}}/clienten
Authorization: Bearer {{login.response.body.jwt}}
Content-Type: application/json
###